plugins:
  packages: de.christianmahnke.lab.iiif.hymir

custom:
  image:
    quality:
      noop:
        enabled: true
      background:
        name: transparent-background
        enabled: true
      fold:
        name: nofold
        enabled: true
      stack:
        name: nofold+transparentbg
        enabled: true
        plugins: nofold,transparent-background
  iiif:
    identifier:
      escape: false

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: plugins