name: Hymir Quality Services build

on:
  push:
    branches:
      - main

jobs:
  build_api:
    runs-on: ubuntu-latest

    steps:
      - name: "Chekout IIIF API (local version)"
        uses: actions/checkout@v3
        with:
          repository: 'cmahnke/iiif-apis'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set Maven repository
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{"id": "github", "url": "https://maven.pkg.github.com/cmahnke/hymir-quality-services", "snapshots.enabled": "true"},{"id": "central", "url": "https://repo1.maven.org/maven2"}]'
          servers: '[{ "id": "github", "username": "${env.GITHUB_ACTOR}", "password": "${env.GITHUB_TOKEN}" }]'
      - name: Build and publish package with maven
        run: mvn -ntp  -Dfmt.skip -DskipTests -Dmaven.gitcommitid.skip -Dspotbugs.skip=true -DskipLocalStaging=true -DgitHubDeploy deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_server:
    needs: build_api
    runs-on: ubuntu-latest

    steps:
      - name: "Chekout IIIF API (local version)"
        uses: actions/checkout@v3
        with:
          repository: 'cmahnke/iiif-server-hymir'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set Maven repository
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{"id": "github", "url": "https://maven.pkg.github.com/cmahnke/hymir-quality-services", "snapshots.enabled": "true"},{"id": "central", "url": "https://repo1.maven.org/maven2"}]'
          servers: '[{ "id": "github", "username": "${env.GITHUB_ACTOR}", "password": "${env.GITHUB_TOKEN}" }]'
      - name: Build and publish package with maven
        run: mvn --batch-mode -ntp -Dfmt.skip -DskipTests -Dmaven.gitcommitid.skip -Dspotbugs.skip=true -DskipLocalStaging=true -DgitHubDeploy deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: build_server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set Maven repository
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{"id": "github", "url": "https://maven.pkg.github.com/cmahnke/hymir-quality-services", "snapshots.enabled": "true"},{"id": "central", "url": "https://repo1.maven.org/maven2"}]'
          servers: '[{ "id": "github", "username": "${env.GITHUB_ACTOR}", "password": "${env.GITHUB_TOKEN}" }]'
      - name: Build and publish package with maven
        run: mvn --batch-mode -ntp -Dfmt.skip -Dmaven.gitcommitid.skip -Dspotbugs.skip=true -DskipLocalStaging=true -DgitHubDeploy -DrepositoryId=github deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
